name: Build and Push Custom Runner Image

on:
  workflow_dispatch: 

jobs:
  build-and-push:
    name: Image Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      date_tag: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set tag date (YYYYMMDD)
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Push to GHCR
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/gha-runner-custom-image:${{ steps.date.outputs.date }}.${{ github.run_number }}